version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres-database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"